IF( Maya_INCLUDE_DIR AND MAYA_LIBRARIES )
  SET( Maya_FIND_QUIETLY TRUE )
ENDIF( Maya_INCLUDE_DIR AND MAYA_LIBRARIES )

set ( MAYA_INCLUDE_DIRS "$ENV{MAYA_LOCATION}/include" )
set ( MAYA_LIBRARY_DIR "$ENV{MAYA_LOCATION}/lib" )

FIND_LIBRARY( Maya_LIB_Foundation NAMES Foundation PATHS $ENV{MAYA_LOCATION}/lib )
FIND_LIBRARY( Maya_LIB_OpenMaya NAMES OpenMaya PATHS $ENV{MAYA_LOCATION}/lib )
FIND_LIBRARY( Maya_LIB_OpenMayaAnim NAMES OpenMayaAnim PATHS $ENV{MAYA_LOCATION}/lib )
FIND_LIBRARY( Maya_LIB_OpenMayaFX NAMES OpenMayaFX PATHS $ENV{MAYA_LOCATION}/lib )
FIND_LIBRARY( Maya_LIB_OpenMayaRender NAMES OpenMayaRender PATHS $ENV{MAYA_LOCATION}/lib )
FIND_LIBRARY( Maya_LIB_OpenMayaUI NAMES OpenMayaUI PATHS $ENV{MAYA_LOCATION}/lib )

set( MAYA_LIBRARIES ${Maya_LIB_Foundation} ${Maya_LIB_OpenMaya} ${Maya_LIB_OpenMayaAnim} ${Maya_LIB_OpenMayaFX} ${Maya_LIB_OpenMayaRender} ${Maya_LIB_OpenMayaUI} )

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( Maya DEFAULT_MSG MAYA_INCLUDE_DIRS )

#MARK_AS_ADVANCED( MAYA_INCLUDE_DIRS MAYA_LIBRARIES )