IF( OPENEXR_INCLUDE_DIRS AND OPENEXR_LIBRARIES )
  SET( OPENEXR_FIND_QUIETLY TRUE )
ENDIF( OPENEXR_INCLUDE_DIRS AND OPENEXR_LIBRARIES )

SET ( OPENEXR_ROOT $ENV{OPENEXR_ROOT} )
message ( "OPENEXR_ROOT:" ${OPENEXR_ROOT} )

find_path(OPENEXR_INCLUDE_DIRS NAMES OpenEXR/half.h HINTS "${OPENEXR_ROOT}/include" )
#find_path(OPENVDB_INCLUDE_DIRS NAMES openvdb/openvdb.h HINTS "${OPENVDB_ROOT}/include" )
message ( "OPENEXR_INCLUDE_DIRS:" ${OPENEXR_INCLUDE_DIRS} )

set ( __LIB_DIR_HINTS "${OPENEXR_ROOT}/lib" )

FIND_LIBRARY( OPENEXR_LIB_Half NAMES libHalf.a Half PATHS ${__LIB_DIR_HINTS} NO_DEFAULT_PATH )
FIND_LIBRARY( OPENEXR_LIB_Iex NAMES libIex.a PATHS ${__LIB_DIR_HINTS} NO_DEFAULT_PATH )
FIND_LIBRARY( OPENEXR_LIB_IexMath NAMES libIexMath.a PATHS ${__LIB_DIR_HINTS} NO_DEFAULT_PATH )
FIND_LIBRARY( OPENEXR_LIB_Imath NAMES libImath.a PATHS ${__LIB_DIR_HINTS} NO_DEFAULT_PATH )
FIND_LIBRARY( OPENEXR_LIB_IlmThread NAMES libIlmThread.a PATHS ${__LIB_DIR_HINTS} NO_DEFAULT_PATH )

set( OPENEXR_LIBRARIES " ")
list(APPEND OPENEXR_LIBRARIES ${OPENEXR_LIB_Half} " " )
list(APPEND OPENEXR_LIBRARIES ${OPENEXR_LIB_Iex} " " )
list(APPEND OPENEXR_LIBRARIES ${OPENEXR_LIB_IexMath} " " )
list(APPEND OPENEXR_LIBRARIES ${OPENEXR_LIB_Imath} " " )
list(APPEND OPENEXR_LIBRARIES ${OPENEXR_LIB_IlmThread} " " )

message ( "OPENEXR_LIBRARIES:" ${OPENEXR_LIBRARIES} )

get_filename_component( OPENEXR_LIBRARY_DIRS ${OPENEXR_LIB_Half} PATH )

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( OPENEXR DEFAULT_MSG OPENEXR_LIBRARIES OPENEXR_LIBRARY_DIRS OPENEXR_INCLUDE_DIRS )

#MARK_AS_ADVANCED( OPENEXR_INCLUDE_DIRS OPENEXR_LIBRARIES )